### ISSUE TITLE
FYI: Reproducible example notebook

### ISSUE THREAD

**Issue by MaxGhenis** [jsvine/weightedcalcs#8]
I wanted to run through your example notebook, so made [this version of it](https://colab.research.google.com/gist/MaxGhenis/4c96163eacebc1005419c9533a568c7e/weightedcalcs-example-usage-scf.ipynb) which instead uses the 2016 Survey of Consumer Finances. This has the advantage of being hosted directly by the government, so anyone can run the full thing as-is (it downloads the data), e.g. in Google Colab as the above link does.

[This version](https://colab.research.google.com/drive/1qRNO3mp4aJ7KQ8lIiP4uxsUDpko-8X_q) also removes the adult limitation, which isn't relevant at the household level (all SCF household heads are 18+).

Feel free to link it if you'd like.

**Comment by jsvine** [comment]
Thanks @MaxGhenis! Very neat. I’ve now added a link to your notebook.
