### ISSUE TITLE
pandas.np deprecation causing warning

### ISSUE THREAD

**Issue by simon-smart88** [jsvine/weightedcalcs#9]
First off thanks for the package - it's a tremendous help!

Recently though this line:

https://github.com/jsvine/weightedcalcs/blob/f70fe2d3e39b928b283667b9e51e233a540655b3/weightedcalcs/core.py#L71

Has been causing:

`FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead.`

I think it may be possible to convert that to `pd.NA` instead though rather than importing numpy.

**Comment by jsvine** [comment]
Good catch, thanks! Now fixed in https://github.com/jsvine/weightedcalcs/commit/852d0226def9a03624d6f87fc833b03b85fbcda5 and available in `0.1.3`.
